// mob_nif.m — Mob UI NIF for iOS (SwiftUI).
// Module name: mob_nif
//
// NIFs build a MobNode tree, then set_root/1 pushes it to MobViewModel where
// SwiftUI re-renders reactively. No UIKit calls here; no dispatch_sync needed.
//
// Thread safety: MobNode mutations happen on the BEAM scheduler thread.
// set_root dispatches to the main thread via MobViewModel.setRoot(), which
// is @Published and fires the SwiftUI diff on the correct thread.
//
// Memory: MobNode* objects are stored as void* using CFBridgingRetain (+1
// manual retain outside ARC). The NIF resource destructor balances with
// CFRelease.

#import <Foundation/Foundation.h>
#include <string.h>
#include "erl_nif.h"
#import "MobNode.h"
// Generated by swiftc -emit-objc-header; exposes MobViewModel and MobUIFactory.
#import "MobDemo-Swift.h"

#define LOG_TAG "MobNIF"
#define LOGI(...) NSLog(@"[MobNIF] " __VA_ARGS__)
#define LOGE(...) NSLog(@"[MobNIF][ERROR] " __VA_ARGS__)

// ── View resource ─────────────────────────────────────────────────────────────

typedef struct {
    CFTypeRef node;       // retained MobNode* (CFBridgingRetain)
    ErlNifPid tap_pid;
    int       has_tap_pid;
} ViewRes;

static ErlNifResourceType* view_res_type = NULL;

// ── Helpers ───────────────────────────────────────────────────────────────────

static int get_string(ErlNifEnv* env, ERL_NIF_TERM term, char* buf, size_t size) {
    ErlNifBinary bin;
    if (enif_inspect_binary(env, term, &bin)) {
        size_t len = bin.size < size - 1 ? bin.size : size - 1;
        memcpy(buf, bin.data, len);
        buf[len] = 0;
        return 1;
    }
    return enif_get_string(env, term, buf, size, ERL_NIF_UTF8) > 0;
}

static UIColor* color_from_argb(long argb) {
    CGFloat a = ((argb >> 24) & 0xFF) / 255.0;
    CGFloat r = ((argb >> 16) & 0xFF) / 255.0;
    CGFloat g = ((argb >>  8) & 0xFF) / 255.0;
    CGFloat b = ((argb >>  0) & 0xFF) / 255.0;
    return [UIColor colorWithRed:r green:g blue:b alpha:a];
}

// ── Resource destructor ───────────────────────────────────────────────────────

static void view_destructor(ErlNifEnv* env, void* ptr) {
    ViewRes* res = (ViewRes*)ptr;
    if (res->node) CFRelease(res->node);
}

// ── Helper: wrap a MobNode into an Erlang resource ───────────────────────────

static ERL_NIF_TERM make_view(ErlNifEnv* env, MobNode* node) {
    ViewRes* res = enif_alloc_resource(view_res_type, sizeof(ViewRes));
    res->node        = CFBridgingRetain(node);
    res->has_tap_pid = 0;
    ERL_NIF_TERM term = enif_make_resource(env, res);
    enif_release_resource(res);
    return term;
}

// ── NIF: log/1 ────────────────────────────────────────────────────────────────

static ERL_NIF_TERM nif_log(ErlNifEnv* env, int argc, const ERL_NIF_TERM argv[]) {
    char buf[512] = {0};
    if (!get_string(env, argv[0], buf, sizeof(buf)))
        return enif_make_badarg(env);
    NSLog(@"[mob] %s", buf);
    return enif_make_atom(env, "ok");
}

// ── NIF: log/2 ────────────────────────────────────────────────────────────────

static ERL_NIF_TERM nif_log2(ErlNifEnv* env, int argc, const ERL_NIF_TERM argv[]) {
    char level[16] = {0};
    char buf[4096] = {0};
    enif_get_atom(env, argv[0], level, sizeof(level), ERL_NIF_LATIN1);
    if (!get_string(env, argv[1], buf, sizeof(buf)))
        return enif_make_badarg(env);
    NSLog(@"[%s] %s", level, buf);
    return enif_make_atom(env, "ok");
}

// ── NIF: create_column/0 ─────────────────────────────────────────────────────

static ERL_NIF_TERM nif_create_column(ErlNifEnv* env, int argc, const ERL_NIF_TERM argv[]) {
    MobNode* node = [[MobNode alloc] init];
    node.nodeType = MobNodeTypeColumn;
    return enif_make_tuple2(env, enif_make_atom(env, "ok"), make_view(env, node));
}

// ── NIF: create_row/0 ────────────────────────────────────────────────────────

static ERL_NIF_TERM nif_create_row(ErlNifEnv* env, int argc, const ERL_NIF_TERM argv[]) {
    MobNode* node = [[MobNode alloc] init];
    node.nodeType = MobNodeTypeRow;
    return enif_make_tuple2(env, enif_make_atom(env, "ok"), make_view(env, node));
}

// ── NIF: create_label/1 ──────────────────────────────────────────────────────

static ERL_NIF_TERM nif_create_label(ErlNifEnv* env, int argc, const ERL_NIF_TERM argv[]) {
    char text[512] = {0};
    if (!get_string(env, argv[0], text, sizeof(text)))
        return enif_make_badarg(env);

    MobNode* node = [[MobNode alloc] init];
    node.nodeType = MobNodeTypeLabel;
    node.text     = [NSString stringWithUTF8String:text];
    return enif_make_tuple2(env, enif_make_atom(env, "ok"), make_view(env, node));
}

// ── NIF: create_button/1 ─────────────────────────────────────────────────────

static ERL_NIF_TERM nif_create_button(ErlNifEnv* env, int argc, const ERL_NIF_TERM argv[]) {
    char text[256] = {0};
    if (!get_string(env, argv[0], text, sizeof(text)))
        return enif_make_badarg(env);

    MobNode* node = [[MobNode alloc] init];
    node.nodeType = MobNodeTypeButton;
    node.text     = [NSString stringWithUTF8String:text];
    return enif_make_tuple2(env, enif_make_atom(env, "ok"), make_view(env, node));
}

// ── NIF: create_scroll/0 ─────────────────────────────────────────────────────

static ERL_NIF_TERM nif_create_scroll(ErlNifEnv* env, int argc, const ERL_NIF_TERM argv[]) {
    MobNode* node = [[MobNode alloc] init];
    node.nodeType = MobNodeTypeScroll;
    return enif_make_tuple2(env, enif_make_atom(env, "ok"), make_view(env, node));
}

// ── NIF: add_child/2 ─────────────────────────────────────────────────────────

static ERL_NIF_TERM nif_add_child(ErlNifEnv* env, int argc, const ERL_NIF_TERM argv[]) {
    ViewRes *parent_res, *child_res;
    if (!enif_get_resource(env, argv[0], view_res_type, (void**)&parent_res) ||
        !enif_get_resource(env, argv[1], view_res_type, (void**)&child_res))
        return enif_make_badarg(env);

    MobNode* parent = (__bridge MobNode*)parent_res->node;
    MobNode* child  = (__bridge MobNode*)child_res->node;
    [parent.children addObject:child];
    return enif_make_atom(env, "ok");
}

// ── NIF: remove_child/1 ──────────────────────────────────────────────────────

static ERL_NIF_TERM nif_remove_child(ErlNifEnv* env, int argc, const ERL_NIF_TERM argv[]) {
    ViewRes* res;
    if (!enif_get_resource(env, argv[0], view_res_type, (void**)&res))
        return enif_make_badarg(env);

    MobNode* node = (__bridge MobNode*)res->node;
    // Remove from parent: scan the view model root tree if needed.
    // For now, remove from parent's children by identity.
    // This is a simplified implementation; full parent tracking can be added later.
    LOGI(@"remove_child: node=%@", node);
    return enif_make_atom(env, "ok");
}

// ── NIF: set_text/2 ──────────────────────────────────────────────────────────

static ERL_NIF_TERM nif_set_text(ErlNifEnv* env, int argc, const ERL_NIF_TERM argv[]) {
    ViewRes* res;
    char text[512] = {0};
    if (!enif_get_resource(env, argv[0], view_res_type, (void**)&res) ||
        !get_string(env, argv[1], text, sizeof(text)))
        return enif_make_badarg(env);

    MobNode* node = (__bridge MobNode*)res->node;
    node.text = [NSString stringWithUTF8String:text];
    return enif_make_atom(env, "ok");
}

// ── NIF: set_text_size/2 ─────────────────────────────────────────────────────

static ERL_NIF_TERM nif_set_text_size(ErlNifEnv* env, int argc, const ERL_NIF_TERM argv[]) {
    ViewRes* res;
    double sz;
    if (!enif_get_resource(env, argv[0], view_res_type, (void**)&res))
        return enif_make_badarg(env);
    if (!enif_get_double(env, argv[1], &sz)) {
        int ival;
        if (!enif_get_int(env, argv[1], &ival))
            return enif_make_badarg(env);
        sz = (double)ival;
    }

    MobNode* node = (__bridge MobNode*)res->node;
    node.textSize = (CGFloat)sz;
    return enif_make_atom(env, "ok");
}

// ── NIF: set_text_color/2 ────────────────────────────────────────────────────

static ERL_NIF_TERM nif_set_text_color(ErlNifEnv* env, int argc, const ERL_NIF_TERM argv[]) {
    ViewRes* res;
    long color;
    if (!enif_get_resource(env, argv[0], view_res_type, (void**)&res) ||
        !enif_get_long(env, argv[1], &color))
        return enif_make_badarg(env);

    MobNode* node = (__bridge MobNode*)res->node;
    node.textColor = color_from_argb(color);
    return enif_make_atom(env, "ok");
}

// ── NIF: set_background_color/2 ──────────────────────────────────────────────

static ERL_NIF_TERM nif_set_background_color(ErlNifEnv* env, int argc, const ERL_NIF_TERM argv[]) {
    ViewRes* res;
    long color;
    if (!enif_get_resource(env, argv[0], view_res_type, (void**)&res) ||
        !enif_get_long(env, argv[1], &color))
        return enif_make_badarg(env);

    MobNode* node = (__bridge MobNode*)res->node;
    node.backgroundColor = color_from_argb(color);
    return enif_make_atom(env, "ok");
}

// ── NIF: set_padding/2 ───────────────────────────────────────────────────────

static ERL_NIF_TERM nif_set_padding(ErlNifEnv* env, int argc, const ERL_NIF_TERM argv[]) {
    ViewRes* res;
    int dp;
    if (!enif_get_resource(env, argv[0], view_res_type, (void**)&res) ||
        !enif_get_int(env, argv[1], &dp))
        return enif_make_badarg(env);

    MobNode* node = (__bridge MobNode*)res->node;
    node.padding = (CGFloat)dp;
    return enif_make_atom(env, "ok");
}

// ── NIF: on_tap/2 ─────────────────────────────────────────────────────────────

static ERL_NIF_TERM nif_on_tap(ErlNifEnv* env, int argc, const ERL_NIF_TERM argv[]) {
    ViewRes* res;
    ErlNifPid pid;
    if (!enif_get_resource(env, argv[0], view_res_type, (void**)&res) ||
        !enif_get_local_pid(env, argv[1], &pid))
        return enif_make_badarg(env);

    res->tap_pid     = pid;
    res->has_tap_pid = 1;

    // Capture the pid by value in the block. Inside the block we make a mutable
    // copy so we can take its address for enif_send (which takes ErlNifPid*).
    ErlNifPid captured_pid = pid;
    MobNode* node = (__bridge MobNode*)res->node;
    node.onTap = ^{
        ErlNifPid local_pid = captured_pid;
        ErlNifEnv* msg_env = enif_alloc_env();
        ERL_NIF_TERM msg = enif_make_tuple2(msg_env,
            enif_make_atom(msg_env, "tap"),
            enif_make_atom(msg_env, "ok"));
        enif_send(NULL, &local_pid, msg_env, msg);
        enif_free_env(msg_env);
    };

    return enif_make_atom(env, "ok");
}

// ── NIF: set_root/1 ──────────────────────────────────────────────────────────

static ERL_NIF_TERM nif_set_root(ErlNifEnv* env, int argc, const ERL_NIF_TERM argv[]) {
    ViewRes* res;
    if (!enif_get_resource(env, argv[0], view_res_type, (void**)&res))
        return enif_make_badarg(env);

    MobNode* node = (__bridge MobNode*)res->node;
    [[MobViewModel shared] setRoot:node];
    LOGI(@"set_root: pushed node type=%ld", (long)node.nodeType);
    return enif_make_atom(env, "ok");
}

static ERL_NIF_TERM nif_platform(ErlNifEnv* env, int argc, const ERL_NIF_TERM argv[]) {
    return enif_make_atom(env, "ios");
}

// ── NIF table & load ─────────────────────────────────────────────────────────

static ErlNifFunc nif_funcs[] = {
    {"platform",              0, nif_platform,             0},
    {"log",                  1, nif_log,                  0},
    {"log",                  2, nif_log2,                 0},
    {"create_column",        0, nif_create_column,        0},
    {"create_row",           0, nif_create_row,           0},
    {"create_label",         1, nif_create_label,         0},
    {"create_button",        1, nif_create_button,        0},
    {"create_scroll",        0, nif_create_scroll,        0},
    {"add_child",            2, nif_add_child,            0},
    {"remove_child",         1, nif_remove_child,         0},
    {"set_text",             2, nif_set_text,             0},
    {"set_text_size",        2, nif_set_text_size,        0},
    {"set_text_color",       2, nif_set_text_color,       0},
    {"set_background_color", 2, nif_set_background_color, 0},
    {"set_padding",          2, nif_set_padding,          0},
    {"on_tap",               2, nif_on_tap,               0},
    {"set_root",             1, nif_set_root,             0},
};

static int nif_load(ErlNifEnv* env, void** priv, ERL_NIF_TERM info) {
    LOGI(@"nif_load: initialising mob_nif (iOS/SwiftUI)");
    view_res_type = enif_open_resource_type(env, NULL, "mob_view",
        view_destructor, ERL_NIF_RT_CREATE | ERL_NIF_RT_TAKEOVER, NULL);
    if (!view_res_type) {
        LOGE(@"nif_load: enif_open_resource_type failed");
        return -1;
    }
    LOGI(@"nif_load: mob_nif ready");
    return 0;
}

ERL_NIF_INIT(mob_nif, nif_funcs, nif_load, NULL, NULL, NULL)
